# Generated by Django 5.2.6 on 2025-11-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='program_type',
            field=models.CharField(max_length=255),
        ),
    ]
