# Generated by Django 5.2.6 on 2025-10-30 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('challenge_type', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('difficulty', models.CharField(max_length=255)),
                ('duration_days', models.IntegerField(default=0)),
                ('image_url', models.TextField(default='')),
                ('instructions', models.TextField(default='')),
                ('max_participants', models.IntegerField(default=0)),
                ('participants_count', models.IntegerField(default=0)),
                ('prize', models.TextField(default='')),
                ('rules', models.JSONField(default=list)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('content_type', models.CharField(max_length=255)),
                ('file_size', models.CharField(max_length=255)),
                ('video_filename', models.TextField()),
                ('video_url', models.TextField()),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.videosubmissionstatus')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
